//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_SBExpertAppSuggestion.h"

@interface _SBExpertLocationAppSuggestion : _SBExpertAppSuggestion
{
}

- (_Bool)isLocationPredictionFromSource:(unsigned long long)arg1;
- (_Bool)isLocationPredictionOfType:(unsigned long long)arg1;
- (id)suggestedLocationName;
- (id)launchURL;
- (id)originatingBundleIdentifier;
- (id)makeInboxCopyOfLaunchURLToInboxURL:(id)arg1;
- (_Bool)launchURLRequiresInboxCopy;
- (_Bool)isEligibleForLockScreen;

@end

