//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBSteppedAnimationTimingFunctionCalculator.h"

@interface _SBMinusPageStepper : SBSteppedAnimationTimingFunctionCalculator
{
}

@property(readonly, nonatomic) double iconsAlpha;
@property(readonly, nonatomic) double searchViewAlpha;
@property(readonly, nonatomic) double pageControlAlpha;
@property(readonly, nonatomic) double backgroundBlurAlpha;
- (id)init;

@end

