//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSMutableSceneClientSettings, FBSSceneClientSettingsDiff, FBSSceneTransitionContext, FBUIScene, NSError, NSSet;

@protocol FBUISceneDelegate <NSObject>

@optional
- (void)scene:(FBUIScene *)arg1 didDeactivateWithError:(NSError *)arg2;
- (void)scene:(FBUIScene *)arg1 willActivateWithTransitionContext:(FBSSceneTransitionContext *)arg2;
- (_Bool)scene:(FBUIScene *)arg1 handleIncomingActions:(NSSet *)arg2;
- (void)scene:(FBUIScene *)arg1 didUpdateClientSettingsWithDiff:(FBSSceneClientSettingsDiff *)arg2;
- (void)scene:(FBUIScene *)arg1 configureInitialClientSettings:(FBSMutableSceneClientSettings *)arg2;
@end

