//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIColor;

@protocol MTMaterialOverlaySettings <NSObject>
@property(nonatomic) double secondaryOverlayTintAlpha;
@property(readonly, copy, nonatomic) UIColor *secondaryOverlayTintColor;
@property(nonatomic) double primaryOverlayTintAlpha;
@property(readonly, copy, nonatomic) UIColor *primaryOverlayTintColor;
@end

