//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSAnalyticsState;

@protocol SBAnalyticsBackendEventContextProviding <NSObject>
@property(readonly, nonatomic) SBSAnalyticsState *eventPayload;
- (void)stateForQueryName:(unsigned long long)arg1 completion:(void (^)(SBSAnalyticsState *))arg2;
@end

