//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoard/FBApplicationPlaceholder.h>

@class NSString;

@interface SBApplicationPlaceholderProxy : FBApplicationPlaceholder
{
    NSString *_customIconClassName;
}

@property(copy) NSString *customIconClassName; // @synthesize customIconClassName=_customIconClassName;
- (void).cxx_destruct;
@property(readonly, nonatomic) Class iconClass;
- (void)_reloadFromProxy:(id)arg1;

@end

