//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBAssistantController;

@protocol SBAssistantObserver <NSObject>

@optional
- (void)assistant:(SBAssistantController *)arg1 viewDidDisappear:(long long)arg2;
- (void)assistant:(SBAssistantController *)arg1 viewWillDisappear:(long long)arg2;
- (void)assistant:(SBAssistantController *)arg1 viewDidAppear:(long long)arg2;
- (void)assistant:(SBAssistantController *)arg1 viewWillAppear:(long long)arg2;
@end

