//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUISettings.h"

@interface SBCarDisplaySettings : SBUISettings
{
    _Bool _animateLockOutModeChanges;
    long long _lockOutMode;
    long long _pairingOverride;
    long long _wirelessOverride;
}

+ (id)settingsControllerModule;
@property long long wirelessOverride; // @synthesize wirelessOverride=_wirelessOverride;
@property long long pairingOverride; // @synthesize pairingOverride=_pairingOverride;
@property long long lockOutMode; // @synthesize lockOutMode=_lockOutMode;
@property _Bool animateLockOutModeChanges; // @synthesize animateLockOutModeChanges=_animateLockOutModeChanges;
- (void)setDefaultValues;

@end

