//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SBApplicationHosting-Protocol.h"
#import "SBCoverSheetSlidingViewControllerContentViewController-Protocol.h"
#import "SBHomeGestureParticipantDelegate-Protocol.h"

@class NSString, SBDashBoardHostedAppViewController, SBHomeGestureParticipant, UIView;
@protocol BSInvalidatable, SBCoverSheetSecureAppEnvironmentViewControllerDelegate;

@interface SBCoverSheetSecureAppEnvironmentViewController : UIViewController <SBHomeGestureParticipantDelegate, SBApplicationHosting, SBCoverSheetSlidingViewControllerContentViewController>
{
    id <BSInvalidatable> _biometricMatchingAssertion;
    SBDashBoardHostedAppViewController *_secureAppViewController;
    UIView *_maskingView;
    id <SBCoverSheetSecureAppEnvironmentViewControllerDelegate> _delegate;
    SBHomeGestureParticipant *_homeGestureParticipant;
}

@property(retain, nonatomic) SBHomeGestureParticipant *homeGestureParticipant; // @synthesize homeGestureParticipant=_homeGestureParticipant;
@property(nonatomic) __weak id <SBCoverSheetSecureAppEnvironmentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIView *maskingView; // @synthesize maskingView=_maskingView;
@property(readonly, nonatomic) SBDashBoardHostedAppViewController *secureAppViewController; // @synthesize secureAppViewController=_secureAppViewController;
- (void).cxx_destruct;
- (void)relinquishHiddenAssertionForHomeGrabber:(id)arg1 animated:(_Bool)arg2;
- (void)takeHiddenAssertionForHomeGrabber:(id)arg1 animated:(_Bool)arg2;
- (void)updateHomeGrabberHiddenAssertion:(_Bool)arg1;
- (void)homeGestureParticipantOwningHomeGestureDidChange:(id)arg1;
- (void)relinquishHomeGesture;
- (void)requestHomeGestureOwnership;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)arg1;
- (id)hostedApp;
- (_Bool)isHostingAnApp;
- (_Bool)canHostAnApp;
@property(readonly, nonatomic) _Bool contentOccludesBackground;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithSecureAppViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

