//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBCrossfadeZoomSettings.h"

@class SBAnimationSettings;

@interface SBCrossfadeAppTransitionSettings : SBCrossfadeZoomSettings
{
    SBAnimationSettings *_appSnapshotCornerRadiusSettings;
}

+ (id)settingsControllerModule;
@property(retain) SBAnimationSettings *appSnapshotCornerRadiusSettings; // @synthesize appSnapshotCornerRadiusSettings=_appSnapshotCornerRadiusSettings;
- (void).cxx_destruct;
- (void)setDefaultValues;

@end

