//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MTMaterialSettings-Protocol.h"

@class MTVibrantStylingProvider, NSString;

@interface SBDeckSwitcherMaterialSettings : NSObject <MTMaterialSettings>
{
}

+ (id)sharedMaterialSettings;
- (void)updateWithSettingsFromArchive:(id)arg1;
@property(readonly, nonatomic) __weak MTVibrantStylingProvider *vibrantStylingProvider;
@property(nonatomic) double tintAlpha;
@property(nonatomic) double brightness;
@property(nonatomic) double saturation;
@property(nonatomic) double luminanceAlpha;
@property(nonatomic) double blurRadius;
@property(nonatomic) _Bool usesLuminanceMap;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

