//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBSleepWakeHardwareButtonInteraction.h"

@interface SBDoubleClickSleepWakeHardwareButtonInteraction : SBSleepWakeHardwareButtonInteraction
{
    _Bool _didSuspendProx;
}

@property(nonatomic) _Bool didSuspendProx; // @synthesize didSuspendProx=_didSuspendProx;
- (void)_resumeProx;
- (void)_suspendProx;
- (void)observeFinalPressUp;
- (_Bool)consumeSecondPressDown;
- (_Bool)consumeInitialPressUp;
- (_Bool)consumeInitialPressDown;

@end

