//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBTransaction.h"

@class SBExternalDisplayController;

@interface SBExternalDisplayWorkspaceSlaveTransaction : SBTransaction
{
    SBExternalDisplayController *_controller;
}

@property(readonly, nonatomic) SBExternalDisplayController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)initWithController:(id)arg1;
- (id)init;

@end

