//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SBFluidSwitcherIconImageContainerViewDelegate-Protocol.h"

@class NSString, SBAppLayout, SBFluidSwitcherIconImageContainerView, UILabel;
@protocol SBFluidSwitcherItemContainerHeaderViewDelegate;

@interface SBFluidSwitcherItemContainerHeaderView : UIView <SBFluidSwitcherIconImageContainerViewDelegate>
{
    SBFluidSwitcherIconImageContainerView *_firstIconImageView;
    UILabel *_firstIconTitle;
    SBFluidSwitcherIconImageContainerView *_secondIconImageView;
    UILabel *_secondIconTitle;
    id <SBFluidSwitcherItemContainerHeaderViewDelegate> _delegate;
    SBAppLayout *_appLayout;
    double _titleAlpha;
}

+ (struct SBSwitcherItemContainerHeaderMetrics)metrics;
@property(nonatomic) double titleAlpha; // @synthesize titleAlpha=_titleAlpha;
@property(retain, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
- (void).cxx_destruct;
- (_Bool)isContainerVisibleFor:(id)arg1;
- (void)_didChangePreferredContentSize:(id)arg1;
- (void)_updateIconsAndTitles;
- (id)_fontForIconLabel;
- (struct CGRect)_frameForSecondIconTitle;
- (struct CGRect)_frameForSecondIconView;
- (void)_createIconAndTitleSubviews;
- (void)_updateTitleAlpha;
- (void)layoutSubviews;
@property(readonly, nonatomic) struct CGRect firstTitleRect;
@property(readonly, nonatomic) struct CGRect firstIconRect;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

