//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBFolderController, SBFolderPresentingViewController;
@protocol SBViewControllerTransitionCoordinator, UIViewControllerAnimatedTransitioning, UIViewControllerInteractiveTransitioning;

@protocol SBFolderPresentingViewControllerDelegate <NSObject>

@optional
- (void)folderPresentationController:(SBFolderPresentingViewController *)arg1 willPerformTransitionWithFolder:(SBFolderController *)arg2 presenting:(_Bool)arg3 withTransitionCoordinator:(id <SBViewControllerTransitionCoordinator>)arg4;
- (id <UIViewControllerInteractiveTransitioning>)folderPresentationController:(SBFolderPresentingViewController *)arg1 interactionControllerForAnimationController:(id <UIViewControllerAnimatedTransitioning>)arg2;
- (id <UIViewControllerAnimatedTransitioning>)folderPresentationController:(SBFolderPresentingViewController *)arg1 animationControllerForTransitionWithFolder:(SBFolderController *)arg2 presenting:(_Bool)arg3 animated:(_Bool)arg4;
@end

