//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBGrabberTongue, UIPanGestureRecognizer, UITouch, UIView;

@protocol SBGrabberTongueDelegate <NSObject>
- (_Bool)grabberTongueRequiredOutsideGrabberFreeRegion:(SBGrabberTongue *)arg1;
- (_Bool)grabberTongueRequiredForWholeEdge:(SBGrabberTongue *)arg1;
- (_Bool)grabberTongueOrPullEnabled:(SBGrabberTongue *)arg1;

@optional
- (UIView *)customTongueViewForGrabberTongue:(SBGrabberTongue *)arg1;
- (UIPanGestureRecognizer *)customGestureRecognizerForGrabberTongue:(SBGrabberTongue *)arg1;
- (void)grabberTongueDidPresentInteractively:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueWillPresentInteractively:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueDidDismiss:(SBGrabberTongue *)arg1;
- (void)grabberTongueWillDismiss:(SBGrabberTongue *)arg1;
- (void)grabberTongueWillPresent:(SBGrabberTongue *)arg1;
- (void)grabberTongueCanceledPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueEndedPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueUpdatedPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (void)grabberTongueBeganPulling:(SBGrabberTongue *)arg1 withDistance:(double)arg2 andVelocity:(double)arg3;
- (double)grabberTongueWidthOfActiveEdge:(SBGrabberTongue *)arg1;
- (double)grabberTongueWidthOfGrabberFreeRegion:(SBGrabberTongue *)arg1;
- (double)grabberTongueCenterOnEdge:(SBGrabberTongue *)arg1;
- (_Bool)grabberTongueHonorsAmbiguousActivationMargin:(SBGrabberTongue *)arg1;
- (_Bool)grabberTongue:(SBGrabberTongue *)arg1 shouldReceiveTouch:(UITouch *)arg2;
@end

