//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBFolderContainerView.h"

@interface SBIconContentView : SBFolderContainerView
{
    long long _orientation;
}

@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
- (void)didAddSubview:(id)arg1;
- (id)initWithOrientation:(long long)arg1 statusBarHeight:(double)arg2;

@end

