//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBIconLabelAccessoryView.h"

@class UIImageView;

@interface SBIconCloudLabelAccessoryView : SBIconLabelAccessoryView
{
    UIImageView *_cloudImageView;
}

@property(readonly, nonatomic) UIImageView *cloudImageView; // @synthesize cloudImageView=_cloudImageView;
- (void).cxx_destruct;
- (void)setLegibilitySettings:(id)arg1;
- (id)initWithLabelAccessoryType:(long long)arg1;
- (id)init;

@end

