//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class SBIcon, SBIconView;

@protocol SBIconViewQuerying
- (_Bool)isDisplayingIcon:(SBIcon *)arg1 inLocation:(long long)arg2;
- (SBIconView *)iconViewForIcon:(SBIcon *)arg1 location:(long long)arg2;
@end

