//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIColor, UIImage, _UILegibilitySettings;
@protocol SBLockScreenModalViewDelegate;

@protocol SBLockScreenModalView <NSObject>
@property(retain, nonatomic) UIImage *image;
@property(copy, nonatomic) NSString *footerText;
@property(copy, nonatomic) NSString *secondaryActionButtonText;
@property(retain, nonatomic) UIColor *primaryActionButtonBackgroundColor;
@property(copy, nonatomic) NSString *primaryActionButtonText;
@property(copy, nonatomic) NSString *secondarySubtitleText;
@property(copy, nonatomic) NSString *subtitleText;
@property(copy, nonatomic) NSString *titleText;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(nonatomic) __weak id <SBLockScreenModalViewDelegate> delegate;
@end

