//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIWindow;

@interface SBMainAlertNonHostedAccessoryWrapper : NSObject
{
    _Bool _shouldRestoreFirstResponder;
    UIWindow *_wrappedWindow;
    NSString *_requester;
}

@property(nonatomic) _Bool shouldRestoreFirstResponder; // @synthesize shouldRestoreFirstResponder=_shouldRestoreFirstResponder;
@property(retain, nonatomic) NSString *requester; // @synthesize requester=_requester;
@property(retain, nonatomic) UIWindow *wrappedWindow; // @synthesize wrappedWindow=_wrappedWindow;
- (void).cxx_destruct;
- (void)handleAlertDeactivation;
- (void)handleAlertActivation;

@end

