//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDeviceApplicationSceneViewControlling-Protocol.h"

@protocol SBMedusaDecoratedDeviceApplicationSceneViewControlling <SBDeviceApplicationSceneViewControlling>
@property(nonatomic, getter=isNubViewHighlighted) _Bool nubViewHighlighted;
@property(nonatomic) double statusBarAreaAlpha;
@property(nonatomic) long long statusBarAreaStyle;
- (void)cleanupAnimationContext:(id)arg1;
- (void)executeAnimationContext:(id)arg1;
- (id)prepareAnimationToStatusBarAreaStyle:(long long)arg1;
@end

