//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBPressSequenceRecognizer;

@protocol SBPressSequenceRecognizerDelegate <NSObject>
- (void)pressSequenceRecognizerDidCompleteSequence:(SBPressSequenceRecognizer *)arg1;

@optional
- (void)pressSequenceRecognizerDidFail:(SBPressSequenceRecognizer *)arg1;
- (void)pressSequenceRecognizer:(SBPressSequenceRecognizer *)arg1 didBeginPressDownAtIndex:(unsigned long long)arg2;
@end

