//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSceneLayoutViewController, SBWorkspaceApplicationSceneTransitionContext;

@protocol SBSceneLayoutViewControllerTransitioningDelegate <NSObject>

@optional
- (void)sceneLayoutControllerDidEndLayoutStateTransition:(SBSceneLayoutViewController *)arg1 wasInterrupted:(_Bool)arg2;
- (void)sceneLayoutController:(SBSceneLayoutViewController *)arg1 didBeginLayoutStateTransitionWithContext:(SBWorkspaceApplicationSceneTransitionContext *)arg2;
@end

