//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class SBAppStatusBarSettingsAssertion, UITextView;

@interface SBSMSClass0AboutViewController : UIViewController
{
    UITextView *_aboutContentView;
    SBAppStatusBarSettingsAssertion *_statusBarSettingsAssertion;
}

- (void).cxx_destruct;
- (id)formattedAboutText;
- (void)doneButtonTapped:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

