//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLayoutState.h"

@interface SBStarkLayoutState : SBLayoutState
{
}

- (id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2;

@end

