//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLayoutElementViewController.h"

@interface SBStarkNowPlayingLayoutElementViewController : SBLayoutElementViewController
{
}

- (id)_newDisplayLayoutElementForEntity:(id)arg1;
- (unsigned long long)supportedContentInterfaceOrientations;
- (void)configureWithWorkspaceEntity:(id)arg1 forLayoutElement:(id)arg2 layoutState:(id)arg3 referenceFrame:(struct CGRect)arg4;

@end

