//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUIStarkStartupToAppAnimation.h"

@interface SBUIStarkStartupToNowPlaying : SBUIStarkStartupToAppAnimation
{
}

- (id)__startTransactionDependencyForEntity:(id)arg1;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (id)_createViewToAnimate;
- (id)_progressDependencies;

@end

