//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol UIStatusBarStateObserver;

@protocol UIStatusBarStateProvider <NSObject>
- (void)getStatusBarData:(CDStruct_8a690d05 *)arg1;
- (void)removeStatusBarStateObserver:(id <UIStatusBarStateObserver>)arg1;
- (void)addStatusBarStateObserver:(id <UIStatusBarStateObserver>)arg1;

@optional
- (NSString *)doubleHeightStatusStringForStyle:(long long)arg1;
@end

