//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, UIImage, UITraitCollection;

@protocol UIStatusBarCarPlayDockDataProviding <NSObject>
- (_Bool)shouldDisplayBadgeForBundleIdentifier:(NSString *)arg1;
- (NSString *)callDuration;
- (UIImage *)dockImageForBundleIdentifier:(NSString *)arg1 format:(int)arg2 traitCollection:(UITraitCollection *)arg3;
- (NSString *)activeBundleIdentifier;
- (NSArray *)bundleIdentifiers;
@end

