//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UIStatusBarStyleDelegate-Protocol.h"

@class UIStatusBar_Base;

@protocol UIStatusBarStyleDelegate_SpringBoardOnly <UIStatusBarStyleDelegate>

@optional
- (long long)overridenRequestedStyleFromStyle:(long long)arg1;
- (int)statusBar:(UIStatusBar_Base *)arg1 effectiveStyleOverridesForRequestedStyle:(long long)arg2 overrides:(int)arg3;
@end

