//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _SBStatusBarAreaStyleAnimationContext : NSObject
{
    long long _statusBarAreaStyle;
    id _statusBarHiddenAnimationContext;
}

@property(retain, nonatomic) id statusBarHiddenAnimationContext; // @synthesize statusBarHiddenAnimationContext=_statusBarHiddenAnimationContext;
@property(nonatomic) long long statusBarAreaStyle; // @synthesize statusBarAreaStyle=_statusBarAreaStyle;
- (void).cxx_destruct;

@end

