//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoardUIServices/BSTransaction.h>

#import "SBUIAnimationControllerCoordinating-Protocol.h"

@class NSString;

@interface BSTransaction (SBUIAnimationControllerAdditions) <SBUIAnimationControllerCoordinating>
- (id)coordinatingAnimationControllers;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

