//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CCUIModularControlCenterViewControllerDelegate-Protocol.h"

@class CCUIModularControlCenterCardViewController, UIView;

@protocol CCUIModularControlCenterCardViewControllerDelegate <CCUIModularControlCenterViewControllerDelegate>
- (double)statusTextHeightForControlCenterViewController:(CCUIModularControlCenterCardViewController *)arg1;
- (long long)interfaceOrientationForControlCenterViewController:(CCUIModularControlCenterCardViewController *)arg1;

@optional
- (UIView *)obscuringBackgroundViewForControlCenterViewController:(CCUIModularControlCenterCardViewController *)arg1;
@end

