//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <BaseBoardUI/BSUIScrollView.h>

@interface SBAppSwitcherScrollView : BSUIScrollView
{
    struct CGPoint _previousContentOffset;
    double _previousScrollTime;
    struct CGPoint _rawContentOffsetVelocity;
}

- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGPoint)contentOffsetVelocityConsideringNextContentOffset:(struct CGPoint)arg1;
- (struct CGPoint)contentOffsetVelocity;
- (void)setContentOffset:(struct CGPoint)arg1;

@end

