//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBCarPlayIconImageCache : NSObject
{
}

+ (id)_imageKeyForBundleIdentifier:(id)arg1 inLayout:(id)arg2;
+ (id)_iconImageCache;
+ (id)sharedInstance;
- (void)setIconImage:(id)arg1 forBundleIdentifier:(id)arg2 inLayout:(id)arg3;
- (id)iconImageForBundleIdentifier:(id)arg1 inLayout:(id)arg2;

@end

