//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBHomeScreenButton.h"

@class UITapGestureRecognizer;
@protocol SBCloseBoxViewDelegate;

@interface SBCloseBoxView : SBHomeScreenButton
{
    UITapGestureRecognizer *_actionTapGestureRecognizer;
    id <SBCloseBoxViewDelegate> _delegate;
}

@property(nonatomic) __weak id <SBCloseBoxViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITapGestureRecognizer *actionTapGestureRecognizer; // @synthesize actionTapGestureRecognizer=_actionTapGestureRecognizer;
- (void).cxx_destruct;
- (_Bool)shouldTrack;

@end

