//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBLockScreenNowPlayingController.h"

@class SBDashBoardMediaControlsViewController;

@interface SBDashBoardNowPlayingController : SBLockScreenNowPlayingController
{
    SBDashBoardMediaControlsViewController *_controlsViewController;
}

@property(readonly, nonatomic) SBDashBoardMediaControlsViewController *controlsViewController; // @synthesize controlsViewController=_controlsViewController;
- (void).cxx_destruct;
- (id)initWithMediaController:(id)arg1;

@end

