//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardViewBase.h"

#import "SBDashBoardPageView-Protocol.h"

@class UIViewController;
@protocol SBDashBoardPageViewControllerProtocol;

@interface SBDashBoardPageViewBase : SBDashBoardViewBase <SBDashBoardPageView>
{
    UIViewController<SBDashBoardPageViewControllerProtocol> *_pageViewController;
    double _contentWidth;
}

@property(nonatomic) double contentWidth; // @synthesize contentWidth=_contentWidth;
@property(nonatomic) __weak UIViewController<SBDashBoardPageViewControllerProtocol> *pageViewController; // @synthesize pageViewController=_pageViewController;
- (void).cxx_destruct;

@end

