//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBScreenEdgePanGestureRecognizer.h"

@protocol SBDashBoardDelegatingScreenEdgePanGestureRecognizerDelegate;

@interface SBDashBoardDelegatingScreenEdgePanGestureRecognizer : SBScreenEdgePanGestureRecognizer
{
    id <SBDashBoardDelegatingScreenEdgePanGestureRecognizerDelegate> _interfaceDelegate;
}

@property(nonatomic) __weak id <SBDashBoardDelegatingScreenEdgePanGestureRecognizerDelegate> interfaceDelegate; // @synthesize interfaceDelegate=_interfaceDelegate;
- (void).cxx_destruct;
- (long long)_touchInterfaceOrientation;

@end

