//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUIAnimationStepping-Protocol.h"

@class BSUIAnimationFactory;

@protocol SBDosidoAnimator <SBUIAnimationStepping>
- (void)cancelDosido;
- (void)animateDosidoWithFactory:(BSUIAnimationFactory *)arg1 completion:(void (^)(_Bool))arg2;
@end

