//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoardUIServices/BSAbstractDefaultDomain.h>

@interface SBExternalSettingsDefaults : BSAbstractDefaultDomain
{
}

+ (_Bool)__useDynamicMethodResolution;
@property(nonatomic, getter=isBadgedForSoftwareUpdate) _Bool badgedForSoftwareUpdate;
- (id)init;

@end

