//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBProximitySensorControlling-Protocol.h"

@class NSString;

@interface SBHIDInterface : NSObject <SBProximitySensorControlling>
{
    _Bool _proximityDetectionEnabled;
    unsigned long long _lockState;
}

+ (id)sharedInstance;
- (void)resetProximityCalibration;
@property(nonatomic, getter=isProximityDetectionEnabled) _Bool proximityDetectionEnabled;
- (void)setProximityDetectionAndMultitouchSuspended:(_Bool)arg1 source:(long long)arg2;
- (void)setProximityDetectionSuspended:(_Bool)arg1 multitouchSuspended:(_Bool)arg2 source:(long long)arg3;
- (void)_setLockState:(unsigned long long)arg1 source:(long long)arg2;
@property(readonly, nonatomic, getter=isProximityDetectionSuspended) _Bool proximityDetectionSuspended;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

