//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBAnalyticsStateMachineEventHandler.h"

@class PETGoalConversionEventTracker;

@interface SBIconLaunchMetric : SBAnalyticsStateMachineEventHandler
{
    PETGoalConversionEventTracker *_tracker;
    _Bool _isFolder;
    long long _location;
}

- (void).cxx_destruct;
- (id)init;
- (void)_processAndReportTappedEventPayload:(id)arg1;

@end

