//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class SBIconScrollView;

@protocol SBIconScrollViewDelegate <UIScrollViewDelegate>
- (_Bool)iconScrollView:(SBIconScrollView *)arg1 shouldSetContentOffset:(struct CGPoint)arg2 animated:(_Bool)arg3;
- (void)iconScrollViewDidCancelTouchTracking:(SBIconScrollView *)arg1;
- (void)iconScrollViewWillCancelTouchTracking:(SBIconScrollView *)arg1;
@end

