//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBReusableViewMap.h"

@interface SBIconLabelAccessoryViewMap : SBReusableViewMap
{
}

+ (Class)viewClassForLabelAccessoryType:(long long)arg1;
+ (struct CGSize)labelAccessoryViewSizeForType:(long long)arg1;
- (id)viewForLabelAccessoryType:(long long)arg1;

@end

