//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBWorkspaceApplicationSceneTransitionContextDelegate-Protocol.h"

@class NSHashTable, NSMapTable, NSString, SBLayoutStateTransitionContext, SBSceneManager;

@interface SBLayoutStateTransitionCoordinator : NSObject <SBWorkspaceApplicationSceneTransitionContextDelegate>
{
    NSHashTable *_observerHashTable;
    NSMapTable *_sceneEntityFrameProviderMapTable;
    SBLayoutStateTransitionContext *_transitionContext;
    SBSceneManager *_sceneManager;
}

@property(readonly, nonatomic) __weak SBSceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
@property(readonly, nonatomic) SBLayoutStateTransitionContext *transitionContext; // @synthesize transitionContext=_transitionContext;
- (void).cxx_destruct;
- (id)sceneEntityFrameProviderForLayoutRole:(long long)arg1;
- (void)setSceneEntityFrameProvider:(id)arg1 forLayoutRole:(long long)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)endTransitionWithError:(id)arg1;
- (void)willEndTransition;
- (void)beginTransitionForWorkspaceTransaction:(id)arg1;
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning;
- (id)previousLayoutStateForApplicationTransitionContext:(id)arg1;
- (id)layoutStateForApplicationTransitionContext:(id)arg1;
- (id)init;
- (id)initWithSceneManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

