//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIWindow;

@interface SBMedusaController : NSObject
{
    UIWindow *_floatingDockWindow;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) UIWindow *floatingDockWindow; // @synthesize floatingDockWindow=_floatingDockWindow;
- (void).cxx_destruct;
- (id)init;
- (id)_init;

@end

