//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBNestingViewControllerTransitionObserver-Protocol.h"

@class SBNestingViewController;
@protocol UIViewControllerAnimatedTransitioning, UIViewControllerInteractiveTransitioning;

@protocol SBNestingViewControllerDelegate <SBNestingViewControllerTransitionObserver>

@optional
- (id <UIViewControllerInteractiveTransitioning>)nestingViewController:(SBNestingViewController *)arg1 interactionControllerForAnimationController:(id <UIViewControllerAnimatedTransitioning>)arg2;
- (id <UIViewControllerAnimatedTransitioning>)nestingViewController:(SBNestingViewController *)arg1 animationControllerForOperation:(long long)arg2 onViewController:(SBNestingViewController *)arg3 animated:(_Bool)arg4;
@end

