//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBPasscodeEntryAlertView;

@protocol SBPasscodeEntryAlertViewDelegate <NSObject>

@optional
- (_Bool)passcodeAlertViewShouldAnimatePresentation:(SBPasscodeEntryAlertView *)arg1;
- (_Bool)passcodeAlertViewShouldShowAutomaticallyWhenVisible:(SBPasscodeEntryAlertView *)arg1;
@end

