//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBRestartManager, SBRestartTransitionRequest;

@protocol SBRestartManagerDelegate <NSObject>

@optional
- (void)restartManagerExitImminent:(SBRestartManager *)arg1;
- (void)restartManager:(SBRestartManager *)arg1 willRestartWithTransitionRequest:(SBRestartTransitionRequest *)arg2;
- (void)restartManagerWillReboot:(SBRestartManager *)arg1;
- (void)restartManagerWillShutdown:(SBRestartManager *)arg1;
@end

