//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBGridSwitcherPersonality.h"

@interface SBReduceMotionGridSwitcherPersonality : SBGridSwitcherPersonality
{
    double _lastGridSwipeUpProgress;
}

- (_Bool)_isActiveAppLayout:(unsigned long long)arg1;
- (_Bool)_isScrunchToHomeGestureActive;
- (_Bool)_isAppToSwitcherGestureActive;
- (struct CGRect)_switcherViewBounds;
- (_Bool)shouldAnimateTransitionForContext:(id)arg1;
- (double)_gridSwipeUpGestureScalingProgressForIndex:(unsigned long long)arg1;
- (double)_gridSwipeUpGestureScalingProgress;
- (double)_scaleForSwipingHomeToSwitcher;
- (double)_scaleForSwipingAppUpToSwitcher;
- (double)scaleForControlCenter;
- (struct CGRect)_adjustedControlCenterFrameForSwitcherBringUp:(struct CGRect)arg1;
- (struct CGRect)_adjustedFrameForSwitcherBringUp:(struct CGRect)arg1 index:(unsigned long long)arg2;
- (double)scaleForIndex:(unsigned long long)arg1 mode:(long long)arg2;
- (struct CGRect)frameForIndex:(unsigned long long)arg1 mode:(long long)arg2;
- (double)titleAndIconOpacityForIndex:(unsigned long long)arg1;
- (double)dockProgress;
- (double)switcherOpacity;
- (double)wallpaperScale;
- (double)homeScreenScale;
- (void)didUpdateGesture:(id)arg1;
- (void)didBeginGesture:(id)arg1;

@end

