//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoardUIServices/BSTransaction.h>

@class NSString;

@interface SBSceneLayoutSynchronizeTransitionTransaction : BSTransaction
{
    NSString *_debugName;
}

- (void).cxx_destruct;
- (id)_graphNodeDebugName;
- (_Bool)_canBeInterrupted;
- (void)synchronize;
- (id)initWithDebugName:(id)arg1;
- (id)init;

@end

