//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBSeparatorView : UIView
{
    UIView *_nubView;
    _Bool _nubHighlighted;
}

@property(nonatomic, getter=isNubHighlighted) _Bool nubHighlighted; // @synthesize nubHighlighted=_nubHighlighted;
- (void).cxx_destruct;
@property(readonly, nonatomic) struct CGRect nubRect;
- (id)initWithFrame:(struct CGRect)arg1;

@end

