//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBSetupManager : NSObject
{
    _Bool _inSetupMode;
    _Bool _inSetupModeReadyToExit;
}

+ (id)sharedInstance;
@property(nonatomic, getter=isInSetupModeReadyToExit) _Bool inSetupModeReadyToExit; // @synthesize inSetupModeReadyToExit=_inSetupModeReadyToExit;
- (_Bool)_setInSetupMode:(_Bool)arg1;
- (void)postLaunchCompleteNotificationForSetup;
- (_Bool)setupHasFinishedRestoringFromBackup;
- (_Bool)updateInSetupMode;
@property(readonly, nonatomic, getter=isInSetupMode) _Bool inSetupMode;
- (id)init;

@end

