//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBHardwareButtonInteraction-Protocol.h"

@class NSString, SBBacklightController, SBBannerController, SBLockScreenManager, SBOrientationLockManager, SBScreenWakeAnimationController, SBSoundController, SpringBoard;

@interface SBSleepWakeHardwareButtonInteraction : NSObject <SBHardwareButtonInteraction>
{
    _Bool _inhibitNextSinglePressUp;
    _Bool _SOSGestureActive;
    _Bool _fadeOutInProgressFromLockButtonWhileUnlocked;
    _Bool _undidFadeOutFromLockButton;
    _Bool _didPlayLockSound;
    SBBacklightController *_backlightController;
    SBBannerController *_bannerController;
    SBLockScreenManager *_lockScreenManager;
    SBOrientationLockManager *_orientationLockManager;
    SBScreenWakeAnimationController *_screenWakeAnimationController;
    SBSoundController *_soundController;
    SpringBoard *_SBApp;
}

@property(nonatomic) _Bool didPlayLockSound; // @synthesize didPlayLockSound=_didPlayLockSound;
@property(nonatomic) _Bool undidFadeOutFromLockButton; // @synthesize undidFadeOutFromLockButton=_undidFadeOutFromLockButton;
@property(nonatomic) _Bool fadeOutInProgressFromLockButtonWhileUnlocked; // @synthesize fadeOutInProgressFromLockButtonWhileUnlocked=_fadeOutInProgressFromLockButtonWhileUnlocked;
@property(retain, nonatomic) SpringBoard *SBApp; // @synthesize SBApp=_SBApp;
@property(retain, nonatomic) SBSoundController *soundController; // @synthesize soundController=_soundController;
@property(retain, nonatomic) SBScreenWakeAnimationController *screenWakeAnimationController; // @synthesize screenWakeAnimationController=_screenWakeAnimationController;
@property(retain, nonatomic) SBOrientationLockManager *orientationLockManager; // @synthesize orientationLockManager=_orientationLockManager;
@property(retain, nonatomic) SBLockScreenManager *lockScreenManager; // @synthesize lockScreenManager=_lockScreenManager;
@property(retain, nonatomic) SBBannerController *bannerController; // @synthesize bannerController=_bannerController;
@property(retain, nonatomic) SBBacklightController *backlightController; // @synthesize backlightController=_backlightController;
@property(nonatomic, getter=isSOSGestureActive) _Bool SOSGestureActive; // @synthesize SOSGestureActive=_SOSGestureActive;
@property(nonatomic) _Bool inhibitNextSinglePressUp; // @synthesize inhibitNextSinglePressUp=_inhibitNextSinglePressUp;
- (void).cxx_destruct;
- (void)_playLockSound;
- (void)_performSleep;
- (void)_performWake;
- (_Bool)consumeSinglePressUp;
- (_Bool)consumeInitialPressDown;
- (_Bool)reverseSleepIfNeededAndPossible;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

