//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBAlertAdapter.h"

@interface SBStarkRelockUIAlert : SBAlertAdapter
{
    _Bool _animatingDismiss;
}

- (void)_dismissAndLock;
- (void)_animateDismiss;
- (id)_animationFactory;
- (id)backgroundMaterialDescriptor;
- (long long)swipeDismissalStyle;
- (void)deactivate;
- (void)activate;
- (_Bool)hasTranslucentBackground;
- (void)handleAutoLock;
- (_Bool)handleLockButtonPress;
- (_Bool)handleMenuButtonLongPress;
- (_Bool)handleMenuButtonDoublePress;
- (_Bool)handleHomeButtonPress;
- (_Bool)wantsHomeButtonPress;
- (void)dealloc;
- (id)initWithViewController:(id)arg1;
- (id)init;

@end

