//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUIAnimationController.h"

@class _SBUIStarkZoomUpNowPlayingFromHomeAnimation;

@interface SBUIStarkZoomUpNowPlayingFromHomeAnimation : SBUIAnimationController
{
    _SBUIStarkZoomUpNowPlayingFromHomeAnimation *_animation;
}

- (void).cxx_destruct;
- (id)animationSettings;
- (_Bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (id)initWithToApplicationSceneEntity:(id)arg1 alertImpersonator:(id)arg2 starkScreenController:(id)arg3;

@end

