//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBCoverSheetPresentationManager, SBLockScreenUnlockRequest;

@protocol SBUILockStateProvider <NSObject>
- (void)coverSheetPresentationManager:(SBCoverSheetPresentationManager *)arg1 unlockWithRequest:(SBLockScreenUnlockRequest *)arg2 completion:(void (^)(_Bool))arg3;
- (_Bool)isUILocked;
@end

