//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (SBSnapshoting)
- (void)_generateSnapshotOnQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)sb_generateSnapshotContentsAsynchronouslyOnQueue:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)sb_generateSnapshotContentsSynchronously;
@end

