//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class WGWidgetGroupViewController;

@protocol WGWidgetGroupViewControllerDelegate <UIScrollViewDelegate>

@optional
- (struct UIEdgeInsets)widgetGroupViewController:(WGWidgetGroupViewController *)arg1 contentOccludingInsetsForInterfaceOrientation:(long long)arg2;
- (struct CGSize)widgetGroupViewController:(WGWidgetGroupViewController *)arg1 sizeForInterfaceOrientation:(long long)arg2;
@end

